NitruxSA/breeze-icon-theme

Breeze Dark/actions/toolbar/edit-delete.svg
same than in the breeze folder
=> Update edit-delete.svg in breeze dark

Breeze Dark/actions/toolbar/view-statistics.svg, Breeze/actions/toolbar/view-statistics.svg
=> view-statistics icon

Breeze/apps/software/calligraauthor.svg, Breeze/apps/software/calligrabraindump.svg, Breeze/apps/software/calligraflow.svg, Breeze/apps/software/calligrakarbon.svg, Breeze/apps/software/calligrakexi.svg, Breeze/apps/software/calligrakrita.svg, Breeze/apps/software/calligraplan.svg, Breeze/apps/software/calligrasheets.svg, Breeze/apps/software/calligrastage.svg, Breeze/apps/software/calligrawords.svg
Hi Uri, what do you think. the icon is similar to the LO app icon with a rounded corner like you will find it on the webpage (https://www.calligra.org/sheets/)
I think it is a good idea that the icons for calligra look similar to the LO icons, but with the rounded corner a bit different.
Comments please.
=> calligra app icon

Breeze Dark/actions/toolbar/draw-line.svg, Breeze Dark/actions/toolbar/draw-watercolor.svg, Breeze/actions/toolbar/draw-line.svg, Breeze/actions/toolbar/draw-watercolor.svg
New drawing tool icons (straight line and watercolor brush.)
Issue #52.
=> Add draw-line and draw-watercolor

Breeze Dark/places/user-folders-small/folder-magenta.svg, Breeze Dark/places/user-folders/folder-magenta.svg, Breeze/places/user-folders-small/folder-magenta.svg, Breeze/places/user-folders/folder-magenta.svg
new file:   Breeze Dark/places/user-folders-small/folder-magenta.svg
new file:   Breeze Dark/places/user-folders/folder-magenta.svg
new file:   Breeze/places/user-folders-small/folder-magenta.svg
new file:   Breeze/places/user-folders/folder-magenta.svg
=> New folder: magenta

Breeze/actions/LO_icons_breeze/24x24/lc_addtable.svg, Breeze/actions/LO_icons_breeze/24x24/lc_dbchangedesignmode.svg, Breeze/actions/LO_icons_breeze/24x24/lc_dbdistinctvalues.svg, Breeze/actions/LO_icons_breeze/24x24/lc_dbformedit.svg, Breeze/actions/LO_icons_breeze/24x24/lc_dbformrename.svg, Breeze/actions/LO_icons_breeze/24x24/lc_dbindexdesign.svg, Breeze/actions/LO_icons_breeze/24x24/lc_dbqueryedit.svg, Breeze/actions/LO_icons_breeze/24x24/lc_dbqueryrename.svg, Breeze/actions/LO_icons_breeze/24x24/lc_dbreportedit.svg, Breeze/actions/LO_icons_breeze/24x24/lc_dbreportrename.svg, Breeze/actions/LO_icons_breeze/24x24/lc_dbtableedit.svg, Breeze/actions/LO_icons_breeze/24x24/lc_dbtablerename.svg, Breeze/actions/LO_icons_breeze/24x24/lc_dbviewaliases.svg, Breeze/actions/LO_icons_breeze/24x24/lc_dbviewfunctions.svg, Breeze/actions/LO_icons_breeze/24x24/lc_dbviewtablenames.svg, Breeze/actions/LO_icons_breeze/24x24/lc_dsbeditdoc.svg, Breeze/actions/LO_icons_breeze/24x24/lc_filtercrit.svg, Breeze/actions/LO_icons_breeze/24x24/lc_formfiltered.svg, Breeze/actions/LO_icons_breeze/24x24/lc_hfixedline.svg, Breeze/actions/LO_icons_breeze/24x24/lc_ordercrit.svg, Breeze/actions/LO_icons_breeze/24x24/lc_recsave.svg, Breeze/actions/LO_icons_breeze/24x24/lc_removefiltersort.svg, Breeze/actions/LO_icons_breeze/24x24/lc_sbaexecutesql.svg, Breeze/actions/LO_icons_breeze/24x24/lc_sbanativesql.svg, Breeze/actions/LO_icons_breeze/24x24/lc_vfixedline.svg
Signed-off-by: DarkknightAK <kainz.a@gmail.com>
=> LO base icons

Breeze/status/im-status/user-away-extended.svg
=> add user-away-extended icon

Breeze/status/im-status/user-away-extended.svg
Reverts NitruxSA/plasma-next-icons#81
=> Revert "add user-away-extended icon"

LibreOffice_Breeze/breeze/cmd/lc_edithyperlink.svg, LibreOffice_Breeze/breeze/cmd/lc_insertobject.svg, LibreOffice_Breeze/breeze/cmd/lc_removehyperlink.svg, LibreOffice_Breeze/breeze/cmd/sc_edithyperlink.svg, LibreOffice_Breeze/breeze/cmd/sc_insertobject.svg, LibreOffice_Breeze/breeze/cmd/sc_insertobjectchart.svg, LibreOffice_Breeze/breeze/cmd/sc_removehyperlink.svg, LibreOffice_Breeze/breeze/links.txt
New icon for OLE and
links.txt changed to work with undo redo
Signed-off-by: andreas_ka <kainz.a@gmail.com>
=> LO updateed icons

Breeze Dark/status/im-status/irc-channel-joined.svg, Breeze Dark/status/im-status/irc-channel-parted.svg, Breeze/status/im-status/irc-channel-joined.svg, Breeze/status/im-status/irc-channel-parted.svg
last missing icons for quassel
Signed-off-by: andreas_ka <kainz.a@gmail.com>
=> Quassel IRC channel icons

LibreOffice_Breeze/Makefile, LibreOffice_Breeze/README.md
* Conversion errors fixed on LO icon themes Makefile
* Other small fixes to Makefile
* README.md with instructions added to LO folder.
=> Conversion errors fixed on LO icon themes Makefile and README.md with instructions added to LO folder

Breeze Dark/actions/toolbar/database-index.svg, Breeze Dark/actions/toolbar/edit-select-lasso.svg, Breeze Dark/actions/toolbar/kt-add-feeds.svg, Breeze Dark/actions/toolbar/kt-add-filters.svg, Breeze Dark/actions/toolbar/kt-bandwidth-scheduler.svg, Breeze Dark/actions/toolbar/kt-change-tracker.svg, Breeze Dark/actions/toolbar/kt-check-data.svg, Breeze Dark/actions/toolbar/kt-chunks.svg, Breeze Dark/actions/toolbar/kt-encrypted.svg, Breeze Dark/actions/toolbar/kt-info-widget.svg, Breeze Dark/actions/toolbar/kt-pause.svg, Breeze Dark/actions/toolbar/kt-plugins.svg, Breeze Dark/actions/toolbar/kt-queue-manager.svg, Breeze Dark/actions/toolbar/kt-remove-feeds.svg, Breeze Dark/actions/toolbar/kt-remove-filters.svg, Breeze Dark/actions/toolbar/kt-remove.svg, Breeze Dark/actions/toolbar/kt-restore-defaults.svg, Breeze Dark/actions/toolbar/kt-set-max-download-speed.svg, Breeze Dark/actions/toolbar/kt-set-max-upload-speed.svg, Breeze Dark/actions/toolbar/kt-show-statusbar.svg, Breeze Dark/actions/toolbar/kt-speed-limits.svg, Breeze Dark/actions/toolbar/kt-start-all.svg, Breeze Dark/actions/toolbar/kt-start.svg, Breeze Dark/actions/toolbar/kt-stop-all.svg, Breeze Dark/actions/toolbar/kt-stop.svg, Breeze Dark/apps/toolbar/preferences-other.svg, Breeze Dark/devices/sidebars/media-floppy.svg
there were some breeze icons that are still missing in breeze-dark
=> Missing dark icons

Breeze Dark/actions/toolbar/configure-shortcuts.svg, Breeze Dark/actions/toolbar/games-config-options.svg, Breeze Dark/actions/toolbar/help-contents.svg, Breeze Dark/actions/toolbar/kmouth-phrase-new.svg, Breeze Dark/actions/toolbar/kmouth-phrase.svg, Breeze Dark/actions/toolbar/kmouth-phrasebook.svg, Breeze Dark/actions/toolbar/kmouth-phresebook-new.svg, Breeze/actions/toolbar/kmouth-phrase-new.svg, Breeze/actions/toolbar/kmouth-phrase.svg, Breeze/actions/toolbar/kmouth-phrasebook.svg, Breeze/actions/toolbar/kmouth-phresebook-new.svg, Breeze/apps/software/kmouth.svg
add icons for kmounth (I'm in contact with the developer of kmounth and ask him if he likes the toolbar icons)
=> kmounth icons

Breeze Dark/places/user-folders-small/folder-image.svg, Breeze Dark/places/user-folders-small/folder-txt.svg, Breeze Dark/places/user-folders-small/folder-video.svg, Breeze/places/user-folders-small/folder-image.svg, Breeze/places/user-folders-small/folder-txt.svg, Breeze/places/user-folders-small/folder-video.svg, Breeze/places/user-folders/folder-image.svg, Breeze/places/user-folders/folder-txt.svg, Breeze/places/user-folders/folder-video.svg
=> sorry Uri don't use windows if you have linux

LibreOffice_Breeze/breeze/cmd/lc_diagramaxisx.svg, LibreOffice_Breeze/breeze/cmd/lc_diagramaxisxyz.svg, LibreOffice_Breeze/breeze/cmd/lc_diagramaxisy.svg, LibreOffice_Breeze/breeze/cmd/lc_diagramaxisz.svg, LibreOffice_Breeze/breeze/cmd/lc_insertmenutitles.svg, LibreOffice_Breeze/breeze/cmd/lc_movepagedown.svg, LibreOffice_Breeze/breeze/cmd/lc_movepagefirst.svg, LibreOffice_Breeze/breeze/cmd/lc_movepagelast.svg, LibreOffice_Breeze/breeze/cmd/lc_movepageup.svg, LibreOffice_Breeze/breeze/cmd/lc_outlinefont.svg, LibreOffice_Breeze/breeze/cmd/sc_diagramaxisx.svg, LibreOffice_Breeze/breeze/cmd/sc_diagramaxisxyz.svg, LibreOffice_Breeze/breeze/cmd/sc_diagramaxisy.svg, LibreOffice_Breeze/breeze/cmd/sc_diagramaxisz.svg, LibreOffice_Breeze/breeze/cmd/sc_insertmenutitles.svg, LibreOffice_Breeze/breeze/cmd/sc_movepagedown.svg, LibreOffice_Breeze/breeze/cmd/sc_movepagefirst.svg, LibreOffice_Breeze/breeze/cmd/sc_movepagelast.svg, LibreOffice_Breeze/breeze/cmd/sc_movepageup.svg, LibreOffice_Breeze/breeze/cmd/sc_outlinefont.svg, LibreOffice_Breeze/breeze/cmd/sc_starshapes.signet.svg, LibreOffice_Breeze/breeze/cmd/sidebar-style-large.svg, LibreOffice_Breeze/breeze/cmd/sidebar-style-small.svg, LibreOffice_Breeze/breeze/res/recentdoc_remove.svg, LibreOffice_Breeze/breeze/res/recentdoc_remove_highlighted.svg
=> new LO icons png still in LO git

Breeze/apps/software/filelight.svg, Breeze/apps/software/kfind.svg
=> add two app icons

LibreOffice_Breeze/breeze/cmd/lc_insertendnote.svg, LibreOffice_Breeze/breeze/cmd/lc_printdefault.svg, LibreOffice_Breeze/breeze/cmd/sc_insertendnote.svg, LibreOffice_Breeze/breeze/cmd/sc_printdefault.svg
=> LO icon sync print and endnote

LibreOffice_Breeze/breeze/cmd/lc_insertendnote.svg, LibreOffice_Breeze/breeze/cmd/sc_insertendnote.svg
=> update LO endnote icons

Breeze/actions/toolbar/acrobat.svg, Breeze/actions/toolbar/align-vertical-bottom-out.svg, Breeze/actions/toolbar/align-vertical-top-out.svg, Breeze/actions/toolbar/documentinfo.svg, Breeze/actions/toolbar/object-group.svg, Breeze/actions/toolbar/object-order-back.svg, Breeze/actions/toolbar/object-order-front.svg, Breeze/actions/toolbar/object-order-lower.svg, Breeze/actions/toolbar/object-order-raise.svg, Breeze/actions/toolbar/object-ungroup.svg, Breeze/actions/toolbar/player-volume-muted.svg, Breeze/actions/toolbar/stroke-cap-bevel.svg, Breeze/actions/toolbar/stroke-cap-miter.svg, Breeze/actions/toolbar/view-grid.svg
was used in galaxy
acrobat eo. pdf export in krita
if you like them I'll sync with breeze-dark
=> additional toolbar icons

Breeze/actions/toolbar/edit-select-all.svg
for me the old icon have to much small lines
but you can say no if you don't like the icon uri
=> new select all icon

LibreOffice_Breeze/breeze/cmd/lc_assignlayout.svg, LibreOffice_Breeze/breeze/cmd/lc_deletepage.svg, LibreOffice_Breeze/breeze/cmd/lc_duplicatepage.svg, LibreOffice_Breeze/breeze/cmd/lc_iconsetformatdialog.svg, LibreOffice_Breeze/breeze/cmd/lc_insertmasterpage.svg, LibreOffice_Breeze/breeze/cmd/lc_insertpage.svg, LibreOffice_Breeze/breeze/cmd/lc_pagesetup.svg, LibreOffice_Breeze/breeze/cmd/lc_slidemasterpage.svg, LibreOffice_Breeze/breeze/cmd/sc_assignlayout.svg, LibreOffice_Breeze/breeze/cmd/sc_deletepage.svg, LibreOffice_Breeze/breeze/cmd/sc_duplicatepage.svg, LibreOffice_Breeze/breeze/cmd/sc_insertmasterpage.svg, LibreOffice_Breeze/breeze/cmd/sc_insertpage.svg, LibreOffice_Breeze/breeze/cmd/sc_pagesetup.svg, LibreOffice_Breeze/breeze/cmd/sc_slidemasterpage.svg
=> updated LO icons

Breeze/apps/preferences/nepomuk.svg
=> was used in the dolphin search

Breeze Dark/index.theme, Breeze/actions/toolbar-small-kde/align-horizontal-left-to-anchor.svg, Breeze/actions/toolbar-small-kde/align-horizontal-right-to-anchor.svg, Breeze/actions/toolbar-small-kde/align-vertical-bottom-to-anchor.svg, Breeze/actions/toolbar-small-kde/align-vertical-top-to-anchor.svg, Breeze/index.theme
=> include toolbar-small-kde

Breeze Dark/apps/software-medium/akregator.svg, Breeze/apps/software-medium/akregator.svg
=> update akregator icon according to #204

Breeze/apps/software/kdots.svg
=> update kdots according to #112

Breeze Dark/places/user-folders-small/folder-activities.svg, Breeze Dark/places/user-folders-small/folder-txt.svg, Breeze/categories/start-menu/applications-multimedia.svg, Breeze/index.theme, Breeze/places/user-folders-small/folder-txt.svg, Breeze/places/user-folders/folder-txt.svg
=> updates from the sync with kde:breeze

Breeze/apps/software/calligraauthor.svg, Breeze/apps/software/calligraflow.svg, Breeze/apps/software/calligrakexi.svg, Breeze/apps/software/calligrakrita.svg, Breeze/apps/software/calligraplan.svg, Breeze/apps/software/calligraplanwork.svg, Breeze/apps/software/calligrasheets.svg, Breeze/apps/software/calligrastage.svg, Breeze/apps/software/calligrawords.svg, Breeze/apps/software/camera-web.svg, Breeze/apps/software/ccc_large.svg, Breeze/apps/software/copy.svg, Breeze/apps/software/dropbox.svg, Breeze/apps/software/firefox.svg, Breeze/apps/software/google-chrome-beta.svg, Breeze/apps/software/google-chrome-unstable.svg, Breeze/apps/software/google-chrome.svg, Breeze/apps/software/google-play-music.svg, Breeze/apps/software/pcsx2.svg, Breeze/apps/software/scanner.svg, Breeze/apps/software/steam.svg
sorry but without this links the app icons are not shown.
=> add links to calligra named app icon links

Breeze/actions/toolbar-small/database-index.svg, Breeze/actions/toolbar/database-index.svg
=> new database-index icon according to #119

Breeze/status/toolbar/dropboxstatus-busy.svg, Breeze/status/toolbar/dropboxstatus-busy2.svg, Breeze/status/toolbar/dropboxstatus-idle.svg, Breeze/status/toolbar/dropboxstatus-logo.svg, Breeze/status/toolbar/dropboxstatus-x.svg
I can't test it so please give me feedback if everything works well
=> add dropbox icons for system-tray according to #206 and #223

Breeze Dark/actions/toolbar-small/media-playlist-repeat.svg, Breeze Dark/actions/toolbar-small/media-playlist-shuffle.svg, Breeze Dark/actions/toolbar/media-playlist-repeat.svg, Breeze Dark/actions/toolbar/media-playlist-shuffle.svg, Breeze/actions/toolbar-small/media-playlist-repeat.svg, Breeze/actions/toolbar-small/media-playlist-shuffle.svg, Breeze/actions/toolbar-small/media-record.svg, Breeze/actions/toolbar/media-playlist-repeat.svg, Breeze/actions/toolbar/media-playlist-shuffle.svg
Signed-off-by: darkknightak <kainz.a@gmail.com>
=> media icons for kaffeine eo.

Breeze Dark/index.theme
=> folder isn't available any more (folder structure changed)

Breeze/index.theme, Breeze/mimetypes/file-types-32/application-vnd.oasis.opendocument.text-master.svg, Breeze/mimetypes/file-types-32/image-jpeg.svg, Breeze/mimetypes/file-types-32/image-jpeg2000.svg, Breeze/mimetypes/file-types-32/libreoffice-oasis-text.svg, Breeze/mimetypes/file-types-32/x-office-document.svg, Breeze/places/user-folders-32/folder-activities.svg, Breeze/places/user-folders-32/folder-development.svg, Breeze/places/user-folders-32/folder-sound.svg, Breeze/places/user-folders-32/folder.svg, Breeze/places/user-folders-32/stock_folder.svg
what do you say to the mimetype and places icons for 32px.
=> 32px mimetype and places support

Breeze/apps/software/bomi.svg, Breeze/apps/software/kdiff3.svg, Breeze/apps/software/qbittorrent.svg, Breeze/apps/software/smartgit.svg, Breeze/apps/software/telegram.svg
Signed-off-by: darkknightak <kainz.a@gmail.com>
=> add app icons from @varlesh

Breeze/actions/toolbar/align-horizontal-top-out.svg
Signed-off-by: darkknightak <kainz.a@gmail.com>
=> sync dark with breeze

Breeze Dark/actions/toolbar-gtk/preferences-system.svg, Breeze Dark/actions/toolbar-small/application-menu.svg, Breeze Dark/actions/toolbar/application-menu.svg, Breeze/actions/toolbar-gtk/preferences-system.svg, Breeze/actions/toolbar-small/application-menu.svg, Breeze/actions/toolbar/application-menu.svg
Signed-off-by: darkknightak <kainz.a@gmail.com>
=> change application menu according to VDG Hangout

Breeze/apps/software/plank.svg
Original icon
https://launchpad.net/plank
=> Add plank icon

LibreOffice_Breeze/breeze/framework/res/extension.svg, LibreOffice_Breeze/breeze/framework/res/folder_32.svg, LibreOffice_Breeze/breeze/framework/res/info_26.svg, LibreOffice_Breeze/breeze/framework/res/recent-documents.svg, LibreOffice_Breeze/breeze/framework/res/remote-documents.svg, LibreOffice_Breeze/breeze/res/odb_32_8.svg, LibreOffice_Breeze/breeze/res/odf_32_8.svg, LibreOffice_Breeze/breeze/res/odg_32_8.svg, LibreOffice_Breeze/breeze/res/odp_32_8.svg, LibreOffice_Breeze/breeze/res/ods_32_8.svg, LibreOffice_Breeze/breeze/res/odt_32_8.svg
https://bugs.documentfoundation.org/show_bug.cgi?id=93064
=> Change LO icons for the startCenter see Bug

Breeze Dark/actions/16/hint.svg, Breeze Dark/actions/16/visibility.svg, Breeze Dark/actions/22/hint.svg, Breeze Dark/actions/22/visible.svg, Breeze/actions/16/hint.svg, Breeze/actions/16/visibility.svg, Breeze/actions/22/hint.svg, Breeze/actions/22/visible.svg
=> add hint and visible icons for KPasswordDialog

Breeze Dark/actions/22/window-close.svg, Breeze/actions/22/window-close.svg
think it was my mistake at an push request.
Signed-off-by: andreas kainz <kainz.a@gmail.com>
=> window-close icon was in 16px in folder 22px

Breeze Dark/actions/16/document-export.svg, Breeze Dark/actions/16/document-import.svg
Signed-off-by: andreas kainz <kainz.a@gmail.com>
=> breeze dark wrong icon color

Breeze/apps/48/QtProject-qtcreator.svg, Breeze/mimetypes/16/application-javascript.svg, Breeze/mimetypes/16/application-sql.svg, Breeze/mimetypes/22/application-javascript.svg, Breeze/mimetypes/22/application-sql.svg, Breeze/mimetypes/32/application-javascript.svg, Breeze/mimetypes/32/application-sql.svg, Breeze/mimetypes/64/application-javascript.svg, Breeze/mimetypes/64/application-sql.svg
=> Simple symbolic links for various icons

Breeze/apps/48/clementine.svg
https://github.com/clementine-player/Clementine/blob/master/dist/clementine.desktop#L31
we need the icon named "clementine" for the .desktop file
=> create symlink for clementine

Breeze Dark/emblems/16/vcs-added.svg, Breeze Dark/emblems/16/vcs-conflicting.svg, Breeze Dark/emblems/16/vcs-locally-modified-unstaged.svg, Breeze Dark/emblems/16/vcs-locally-modified.svg, Breeze Dark/emblems/16/vcs-normal.svg, Breeze Dark/emblems/16/vcs-removed.svg, Breeze Dark/emblems/16/vcs-update-required.svg, Breeze/emblems/16/vcs-added.svg, Breeze/emblems/16/vcs-conflicting.svg, Breeze/emblems/16/vcs-locally-modified-unstaged.svg, Breeze/emblems/16/vcs-locally-modified.svg, Breeze/emblems/16/vcs-normal.svg, Breeze/emblems/16/vcs-removed.svg, Breeze/emblems/16/vcs-update-required.svg
=> Add vcs icons

LibreOffice_Breeze/breeze/chart2/res/typegl3dbar_16.svg, LibreOffice_Breeze/breeze/cmd/lc_entirecell.svg, LibreOffice_Breeze/breeze/cmd/lc_setoutline.svg, LibreOffice_Breeze/breeze/cmd/lc_splittable.svg, LibreOffice_Breeze/breeze/cmd/lc_tablenumberformatdialog.svg, LibreOffice_Breeze/breeze/cmd/sc_entirecell.svg, LibreOffice_Breeze/breeze/cmd/sc_setoutline.svg, LibreOffice_Breeze/breeze/cmd/sc_splittable.svg, LibreOffice_Breeze/breeze/cmd/sc_tablenumberformatdialog.svg
Signed-off-by: andreas kainz <kainz.a@gmail.com>
=> new LO 5.1 icons

LibreOffice_Breeze/breeze/cmd/32/diamode.svg, LibreOffice_Breeze/breeze/cmd/32/handoutmode.svg, LibreOffice_Breeze/breeze/cmd/32/normalmultipanegui.svg, LibreOffice_Breeze/breeze/cmd/32/notesmasterpage.svg, LibreOffice_Breeze/breeze/cmd/32/notesmode.svg, LibreOffice_Breeze/breeze/cmd/32/outlinemode.svg, LibreOffice_Breeze/breeze/cmd/lc_diamode.svg, LibreOffice_Breeze/breeze/cmd/lc_handoutmode.svg, LibreOffice_Breeze/breeze/cmd/lc_normalmultipanegui.svg, LibreOffice_Breeze/breeze/cmd/lc_notesmasterpage.svg, LibreOffice_Breeze/breeze/cmd/lc_notesmode.svg, LibreOffice_Breeze/breeze/cmd/lc_outlinemode.svg, LibreOffice_Breeze/breeze/cmd/sc_diamode.svg, LibreOffice_Breeze/breeze/cmd/sc_handoutmode.svg, LibreOffice_Breeze/breeze/cmd/sc_normalmultipanegui.svg, LibreOffice_Breeze/breeze/cmd/sc_notesmasterpage.svg, LibreOffice_Breeze/breeze/cmd/sc_notesmode.svg, LibreOffice_Breeze/breeze/cmd/sc_outlinemode.svg
Signed-off-by: andreas kainz <kainz.a@gmail.com>
=> add LO icons for displaymode

Breeze Dark/apps/48/synfig_icon.svg, Breeze Dark/mimetypes/16/application-x-sif.svg, Breeze Dark/mimetypes/22/application-x-sif.svg, Breeze Dark/mimetypes/32/application-x-sif.svg, Breeze Dark/mimetypes/64/application-x-sif.svg, Breeze/apps/48/synfig_icon.svg, Breeze/mimetypes/16/application-x-sif.svg, Breeze/mimetypes/22/application-x-sif.svg, Breeze/mimetypes/32/application-x-sif.svg, Breeze/mimetypes/64/application-x-sif.svg
thanks for submitting the icons I added them to the kde repository as well so they will ship to the user with the next qt5 framework release in one month.
https://github.com/KDE/breeze-icons/commit/dfa88c23338f360dab3ac9307d2c00f60c9e7a37
#298
=> synfig icons according to issue 298 from aldy-art

Breeze Dark/actions/22/document-save-as-template.svg, Breeze/actions/22/document-save-as-template.svg
This icon could be used to save a document as a template.
=> Add 'document-save-as-template' icon

Breeze Dark/apps/22/fcitx-googlepinyin.svg, Breeze Dark/apps/22/fcitx-pinyin-libpinyin.svg, Breeze Dark/apps/22/fcitx-pinyin.svg, Breeze Dark/apps/22/fcitx-shuangpin-libpinyin.svg, Breeze Dark/apps/22/fcitx-shuangpin.svg, Breeze Dark/apps/22/fcitx-sunpinyin.svg, Breeze Dark/apps/22/fcitx-wubi.svg, Breeze/apps/22/fcitx-googlepinyin.svg, Breeze/apps/22/fcitx-pinyin-libpinyin.svg, Breeze/apps/22/fcitx-pinyin.svg, Breeze/apps/22/fcitx-shuangpin-libpinyin.svg, Breeze/apps/22/fcitx-shuangpin.svg, Breeze/apps/22/fcitx-sunpinyin.svg, Breeze/apps/22/fcitx-wubi.svg
These icons appear in system tray.
=> icons for pinyin input methods in fcitx

Breeze Dark/status/22/update-high.svg, Breeze Dark/status/22/update-low.svg, Breeze Dark/status/22/update-medium.svg, Breeze Dark/status/22/update-none.svg, Breeze/status/22/update-high.svg, Breeze/status/22/update-low.svg, Breeze/status/22/update-medium.svg, Breeze/status/22/update-none.svg
These icons can be used for plasma-pk-updates in system tray.
=> System tray icons for system updates.
